export enum IOrderRealProductStatus {
  ORDER_PENDING = 'ORDER_PENDING', // 확정 대기
  ORDER_CONFIRM = 'ORDER_CONFIRM', // 주문 확정
  ORDER_COMPLETED = 'ORDER_COMPLETED', // 발주 완료
  STORAGE_COMPLETED = 'STORAGE_COMPLETED', // 입고 완료
  DELIVERY_PROGRESS = 'DELIVERY_PROGRESS', // 배송중
  DELIVERY_COMPLETED = 'DELIVERY_COMPLETED', // 배송 완료
  ORDER_CANCELED = 'ORDER_CANCELED', // 주문 취소
  ORDER_EDIT_REQUEST = 'ORDER_EDIT_REQUEST', // 주문 수정 요청
}
