export enum DeliveryCancelIntentStatus {
  PENDING = 'PENDING',
  CANCEL_CONFIRMED = 'CANCEL_CONFIRMED',
  DB_APPLIED = 'DB_APPLIED',
  REFUND_SUCCEEDED = 'REFUND_SUCCEEDED',
  RESOLVED_NO_REFUND = 'RESOLVED_NO_REFUND',
  RECONCILING = 'RECONCILING',
}

export enum DeliveryCancelIntentSource {
  EXTERNAL_API = 'EXTERNAL_API',
  CUSTOMER_SERVICE = 'CUSTOMER_SERVICE',
}

export const DELIVERY_CANCEL_RECONCILE_REQUIRED = 'DELIVERY_CANCEL_RECONCILE_REQUIRED';
