export enum DeliveryTrackingStatus {
  UNKNOWN = 'UNKNOWN',
  INFORMATION_RECEIVED = 'INFORMATION_RECEIVED',
  AT_PICKUP = 'AT_PICKUP',
  IN_TRANSIT = 'IN_TRANSIT',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  ATTEMPT_FAIL = 'ATTEMPT_FAIL',
  DELIVERED = 'DELIVERED',
  AVAILABLE_FOR_PICKUP = 'AVAILABLE_FOR_PICKUP',
  EXCEPTION = 'EXCEPTION',
}
