    INSERT INTO product (
        type,
        code,
        name,
        image_path,
        partner_company_code,
        partner_company_id,
        brand_id,
        price,
        expire_day,
        category,
        classification,
        settle_percent,
        settle_method,
        coupon_method,
        use_status,
        created_at,
        updated_at
    ) VALUES (
                 'CHOICE',
                 'ECPTEST',
                 '테스트 초이스쿠폰',
                 'http://test.xyz/image',
                 '',
                 0,
                 0,
                 1000,
                 60,
                 'C',
                 'classification',
                 30,
                 'PER_EXCHANGE',
                 '',
                 'USE',
                 now(),
                 now()
             );
